class Migration < ActiveRecord::Migration
  def self.up
    create_table :countries do |t|
      t.column :short_name, :string, size: 120
      t.column :alpha2, :string, size: 2
      t.column :alpha3, :string, size: 3
      t.column :numeric, :integer
    end

    Country.create(:short_name => 'Afghanistan', :alpha3 => 'AFG', :alpha2 => 'AF', :numcode => 4)
    Country.create(:short_name => 'Åland Islands', :alpha3 => 'ALA', :alpha2 => 'AX', :numcode => 248)
    Country.create(:short_name => 'Albania', :alpha3 => 'ALB', :alpha2 => 'AL', :numcode => 8)
    Country.create(:short_name => 'Algeria', :alpha3 => 'DZA', :alpha2 => 'DZ', :numcode => 12)
    Country.create(:short_name => 'American Samoa', :alpha3 => 'ASM', :alpha2 => 'AS', :numcode => 16)
    Country.create(:short_name => 'Andorra', :alpha3 => 'AND', :alpha2 => 'AD', :numcode => 20)
    Country.create(:short_name => 'Angola', :alpha3 => 'AGO', :alpha2 => 'AO', :numcode => 24)
    Country.create(:short_name => 'Anguilla', :alpha3 => 'AIA', :alpha2 => 'AI', :numcode => 660)
    Country.create(:short_name => 'Antarctica', :alpha3 => 'ATA', :alpha2 => 'AQ', :numcode => 10)
    Country.create(:short_name => 'Antigua and Barbuda', :alpha3 => 'ATG', :alpha2 => 'AG', :numcode => 28)
    Country.create(:short_name => 'Argentina', :alpha3 => 'ARG', :alpha2 => 'AR', :numcode => 32)
    Country.create(:short_name => 'Armenia', :alpha3 => 'ARM', :alpha2 => 'AM', :numcode => 51)
    Country.create(:short_name => 'Aruba', :alpha3 => 'ABW', :alpha2 => 'AW', :numcode => 533)
    Country.create(:short_name => 'Australia', :alpha3 => 'AUS', :alpha2 => 'AU', :numcode => 36)
    Country.create(:short_name => 'Austria', :alpha3 => 'AUT', :alpha2 => 'AT', :numcode => 40)
    Country.create(:short_name => 'Azerbaijan', :alpha3 => 'AZE', :alpha2 => 'AZ', :numcode => 31)
    Country.create(:short_name => 'Bahamas', :alpha3 => 'BHS', :alpha2 => 'BS', :numcode => 44)
    Country.create(:short_name => 'Bahrain', :alpha3 => 'BHR', :alpha2 => 'BH', :numcode => 48)
    Country.create(:short_name => 'Bangladesh', :alpha3 => 'BGD', :alpha2 => 'BD', :numcode => 50)
    Country.create(:short_name => 'Barbados', :alpha3 => 'BRB', :alpha2 => 'BB', :numcode => 52)
    Country.create(:short_name => 'Belarus', :alpha3 => 'BLR', :alpha2 => 'BY', :numcode => 112)
    Country.create(:short_name => 'Belgium', :alpha3 => 'BEL', :alpha2 => 'BE', :numcode => 56)
    Country.create(:short_name => 'Belize', :alpha3 => 'BLZ', :alpha2 => 'BZ', :numcode => 84)
    Country.create(:short_name => 'Benin', :alpha3 => 'BEN', :alpha2 => 'BJ', :numcode => 204)
    Country.create(:short_name => 'Bermuda', :alpha3 => 'BMU', :alpha2 => 'BM', :numcode => 60)
    Country.create(:short_name => 'Bhutan', :alpha3 => 'BTN', :alpha2 => 'BT', :numcode => 64)
    Country.create(:short_name => 'Bolivia', :alpha3 => 'BOL', :alpha2 => 'BO', :numcode => 68)
    Country.create(:short_name => 'Bosnia and Herzegovina', :alpha3 => 'BIH', :alpha2 => 'BA', :numcode => 70)
    Country.create(:short_name => 'Botswana', :alpha3 => 'BWA', :alpha2 => 'BW', :numcode => 72)
    Country.create(:short_name => 'Bouvet Island', :alpha3 => 'BVT', :alpha2 => 'BV', :numcode => 74)
    Country.create(:short_name => 'Brazil', :alpha3 => 'BRA', :alpha2 => 'BR', :numcode => 76)
    Country.create(:short_name => 'British Indian Ocean Territory', :alpha3 => 'IOT', :alpha2 => 'IO', :numcode => 86)
    Country.create(:short_name => 'Brunei Darussalam', :alpha3 => 'BRN', :alpha2 => 'BN', :numcode => 96)
    Country.create(:short_name => 'Bulgaria', :alpha3 => 'BGR', :alpha2 => 'BG', :numcode => 100)
    Country.create(:short_name => 'Burkina Faso', :alpha3 => 'BFA', :alpha2 => 'BF', :numcode => 854)
    Country.create(:short_name => 'Burundi', :alpha3 => 'BDI', :alpha2 => 'BI', :numcode => 108)
    Country.create(:short_name => 'Cambodia', :alpha3 => 'KHM', :alpha2 => 'KH', :numcode => 116)
    Country.create(:short_name => 'Cameroon', :alpha3 => 'CMR', :alpha2 => 'CM', :numcode => 120)
    Country.create(:short_name => 'Canada', :alpha3 => 'CAN', :alpha2 => 'CA', :numcode => 124)
    Country.create(:short_name => 'Cape Verde', :alpha3 => 'CPV', :alpha2 => 'CV', :numcode => 132)
    Country.create(:short_name => 'Cayman Islands', :alpha3 => 'CYM', :alpha2 => 'KY', :numcode => 136)
    Country.create(:short_name => 'Central African Republic', :alpha3 => 'CAF', :alpha2 => 'CF', :numcode => 140)
    Country.create(:short_name => 'Chad', :alpha3 => 'TCD', :alpha2 => 'TD', :numcode => 148)
    Country.create(:short_name => 'Chile', :alpha3 => 'CHL', :alpha2 => 'CL', :numcode => 152)
    Country.create(:short_name => 'China', :alpha3 => 'CHN', :alpha2 => 'CN', :numcode => 156)
    Country.create(:short_name => 'Christmas Island', :alpha3 => 'CXR', :alpha2 => 'CX', :numcode => 162)
    Country.create(:short_name => 'Cocos (Keeling) Islands', :alpha3 => 'CCK', :alpha2 => 'CC', :numcode => 166)
    Country.create(:short_name => 'Colombia', :alpha3 => 'COL', :alpha2 => 'CO', :numcode => 170)
    Country.create(:short_name => 'Comoros', :alpha3 => 'COM', :alpha2 => 'KM', :numcode => 174)
    Country.create(:short_name => 'Congo', :alpha3 => 'COG', :alpha2 => 'CG', :numcode => 178)
    Country.create(:short_name => 'Congo, the Democratic Republic of the', :alpha3 => 'COD', :alpha2 => 'CD', :numcode => 180)
    Country.create(:short_name => 'Cook Islands', :alpha3 => 'COK', :alpha2 => 'CK', :numcode => 184)
    Country.create(:short_name => 'Costa Rica', :alpha3 => 'CRI', :alpha2 => 'CR', :numcode => 188)
    Country.create(:short_name => 'Croatia', :alpha3 => 'HRV', :alpha2 => 'HR', :numcode => 191)
    Country.create(:short_name => 'Cuba', :alpha3 => 'CUB', :alpha2 => 'CU', :numcode => 192)
    Country.create(:short_name => 'Cyprus', :alpha3 => 'CYP', :alpha2 => 'CY', :numcode => 196)
    Country.create(:short_name => 'Czech Republic', :alpha3 => 'CZE', :alpha2 => 'CZ', :numcode => 203)
    Country.create(:short_name => 'Côte d\'Ivoire', :alpha3 => 'CIV', :alpha2 => 'CI', :numcode => 384)
    Country.create(:short_name => 'Denmark', :alpha3 => 'DNK', :alpha2 => 'DK', :numcode => 208)
    Country.create(:short_name => 'Djibouti', :alpha3 => 'DJI', :alpha2 => 'DJ', :numcode => 262)
    Country.create(:short_name => 'Dominica', :alpha3 => 'DMA', :alpha2 => 'DM', :numcode => 212)
    Country.create(:short_name => 'Dominican Republic', :alpha3 => 'DOM', :alpha2 => 'DO', :numcode => 214)
    Country.create(:short_name => 'Ecuador', :alpha3 => 'ECU', :alpha2 => 'EC', :numcode => 218)
    Country.create(:short_name => 'Egypt', :alpha3 => 'EGY', :alpha2 => 'EG', :numcode => 818)
    Country.create(:short_name => 'El Salvador', :alpha3 => 'SLV', :alpha2 => 'SV', :numcode => 222)
    Country.create(:short_name => 'Equatorial Guinea', :alpha3 => 'GNQ', :alpha2 => 'GQ', :numcode => 226)
    Country.create(:short_name => 'Eritrea', :alpha3 => 'ERI', :alpha2 => 'ER', :numcode => 232)
    Country.create(:short_name => 'Estonia', :alpha3 => 'EST', :alpha2 => 'EE', :numcode => 233)
    Country.create(:short_name => 'Ethiopia', :alpha3 => 'ETH', :alpha2 => 'ET', :numcode => 231)
    Country.create(:short_name => 'Falkland Islands (Malvinas)', :alpha3 => 'FLK', :alpha2 => 'FK', :numcode => 238)
    Country.create(:short_name => 'Faroe Islands', :alpha3 => 'FRO', :alpha2 => 'FO', :numcode => 234)
    Country.create(:short_name => 'Fiji', :alpha3 => 'FJI', :alpha2 => 'FJ', :numcode => 242)
    Country.create(:short_name => 'Finland', :alpha3 => 'FIN', :alpha2 => 'FI', :numcode => 246)
    Country.create(:short_name => 'France', :alpha3 => 'FRA', :alpha2 => 'FR', :numcode => 250)
    Country.create(:short_name => 'French Guiana', :alpha3 => 'GUF', :alpha2 => 'GF', :numcode => 254)
    Country.create(:short_name => 'French Polynesia', :alpha3 => 'PYF', :alpha2 => 'PF', :numcode => 258)
    Country.create(:short_name => 'French Southern Territories', :alpha3 => 'ATF', :alpha2 => 'TF', :numcode => 260)
    Country.create(:short_name => 'Gabon', :alpha3 => 'GAB', :alpha2 => 'GA', :numcode => 266)
    Country.create(:short_name => 'Gambia', :alpha3 => 'GMB', :alpha2 => 'GM', :numcode => 270)
    Country.create(:short_name => 'Georgia', :alpha3 => 'GEO', :alpha2 => 'GE', :numcode => 268)
    Country.create(:short_name => 'Germany', :alpha3 => 'DEU', :alpha2 => 'DE', :numcode => 276)
    Country.create(:short_name => 'Ghana', :alpha3 => 'GHA', :alpha2 => 'GH', :numcode => 288)
    Country.create(:short_name => 'Gibraltar', :alpha3 => 'GIB', :alpha2 => 'GI', :numcode => 292)
    Country.create(:short_name => 'Greece', :alpha3 => 'GRC', :alpha2 => 'GR', :numcode => 300)
    Country.create(:short_name => 'Greenland', :alpha3 => 'GRL', :alpha2 => 'GL', :numcode => 304)
    Country.create(:short_name => 'Grenada', :alpha3 => 'GRD', :alpha2 => 'GD', :numcode => 308)
    Country.create(:short_name => 'Guadeloupe', :alpha3 => 'GLP', :alpha2 => 'GP', :numcode => 312)
    Country.create(:short_name => 'Guam', :alpha3 => 'GUM', :alpha2 => 'GU', :numcode => 316)
    Country.create(:short_name => 'Guatemala', :alpha3 => 'GTM', :alpha2 => 'GT', :numcode => 320)
    Country.create(:short_name => 'Guernsey', :alpha3 => 'GGY', :alpha2 => 'GG', :numcode => 831)
    Country.create(:short_name => 'Guinea', :alpha3 => 'GIN', :alpha2 => 'GN', :numcode => 324)
    Country.create(:short_name => 'Guinea-Bissau', :alpha3 => 'GNB', :alpha2 => 'GW', :numcode => 624)
    Country.create(:short_name => 'Guyana', :alpha3 => 'GUY', :alpha2 => 'GY', :numcode => 328)
    Country.create(:short_name => 'Haiti', :alpha3 => 'HTI', :alpha2 => 'HT', :numcode => 332)
    Country.create(:short_name => 'Heard Island and McDonald Islands', :alpha3 => 'HMD', :alpha2 => 'HM', :numcode => 334)
    Country.create(:short_name => 'Holy See (Vatican City State)', :alpha3 => 'VAT', :alpha2 => 'VA', :numcode => 336)
    Country.create(:short_name => 'Honduras', :alpha3 => 'HND', :alpha2 => 'HN', :numcode => 340)
    Country.create(:short_name => 'Hong Kong', :alpha3 => 'HKG', :alpha2 => 'HK', :numcode => 344)
    Country.create(:short_name => 'Hungary', :alpha3 => 'HUN', :alpha2 => 'HU', :numcode => 348)
    Country.create(:short_name => 'Iceland', :alpha3 => 'ISL', :alpha2 => 'IS', :numcode => 352)
    Country.create(:short_name => 'India', :alpha3 => 'IND', :alpha2 => 'IN', :numcode => 356)
    Country.create(:short_name => 'Indonesia', :alpha3 => 'IDN', :alpha2 => 'ID', :numcode => 360)
    Country.create(:short_name => 'Iran, Islamic Republic of', :alpha3 => 'IRN', :alpha2 => 'IR', :numcode => 364)
    Country.create(:short_name => 'Iraq', :alpha3 => 'IRQ', :alpha2 => 'IQ', :numcode => 368)
    Country.create(:short_name => 'Ireland', :alpha3 => 'IRL', :alpha2 => 'IE', :numcode => 372)
    Country.create(:short_name => 'Isle of Man', :alpha3 => 'IMN', :alpha2 => 'IM', :numcode => 833)
    Country.create(:short_name => 'Israel', :alpha3 => 'ISR', :alpha2 => 'IL', :numcode => 376)
    Country.create(:short_name => 'Italy', :alpha3 => 'ITA', :alpha2 => 'IT', :numcode => 380)
    Country.create(:short_name => 'Jamaica', :alpha3 => 'JAM', :alpha2 => 'JM', :numcode => 388)
    Country.create(:short_name => 'Japan', :alpha3 => 'JPN', :alpha2 => 'JP', :numcode => 392)
    Country.create(:short_name => 'Jersey', :alpha3 => 'JEY', :alpha2 => 'JE', :numcode => 832)
    Country.create(:short_name => 'Jordan', :alpha3 => 'JOR', :alpha2 => 'JO', :numcode => 400)
    Country.create(:short_name => 'Kazakhstan', :alpha3 => 'KAZ', :alpha2 => 'KZ', :numcode => 398)
    Country.create(:short_name => 'Kenya', :alpha3 => 'KEN', :alpha2 => 'KE', :numcode => 404)
    Country.create(:short_name => 'Kiribati', :alpha3 => 'KIR', :alpha2 => 'KI', :numcode => 296)
    Country.create(:short_name => 'Korea, Democratic People\'s Republic of', :alpha3 => 'PRK', :alpha2 => 'KP', :numcode => 408)
    Country.create(:short_name => 'Korea, Republic of', :alpha3 => 'KOR', :alpha2 => 'KR', :numcode => 410)
    Country.create(:short_name => 'Kuwait', :alpha3 => 'KWT', :alpha2 => 'KW', :numcode => 414)
    Country.create(:short_name => 'Kyrgyzstan', :alpha3 => 'KGZ', :alpha2 => 'KG', :numcode => 417)
    Country.create(:short_name => 'Lao People\'s Democratic Republic', :alpha3 => 'LAO', :alpha2 => 'LA', :numcode => 418)
    Country.create(:short_name => 'Latvia', :alpha3 => 'LVA', :alpha2 => 'LV', :numcode => 428)
    Country.create(:short_name => 'Lebanon', :alpha3 => 'LBN', :alpha2 => 'LB', :numcode => 422)
    Country.create(:short_name => 'Lesotho', :alpha3 => 'LSO', :alpha2 => 'LS', :numcode => 426)
    Country.create(:short_name => 'Liberia', :alpha3 => 'LBR', :alpha2 => 'LR', :numcode => 430)
    Country.create(:short_name => 'Libyan Arab Jamahiriya', :alpha3 => 'LBY', :alpha2 => 'LY', :numcode => 434)
    Country.create(:short_name => 'Liechtenstein', :alpha3 => 'LIE', :alpha2 => 'LI', :numcode => 438)
    Country.create(:short_name => 'Lithuania', :alpha3 => 'LTU', :alpha2 => 'LT', :numcode => 440)
    Country.create(:short_name => 'Luxembourg', :alpha3 => 'LUX', :alpha2 => 'LU', :numcode => 442)
    Country.create(:short_name => 'Macao', :alpha3 => 'MAC', :alpha2 => 'MO', :numcode => 446)
    Country.create(:short_name => 'Macedonia, the former Yugoslav Republic of', :alpha3 => 'MKD', :alpha2 => 'MK', :numcode => 807)
    Country.create(:short_name => 'Madagascar', :alpha3 => 'MDG', :alpha2 => 'MG', :numcode => 450)
    Country.create(:short_name => 'Malawi', :alpha3 => 'MWI', :alpha2 => 'MW', :numcode => 454)
    Country.create(:short_name => 'Malaysia', :alpha3 => 'MYS', :alpha2 => 'MY', :numcode => 458)
    Country.create(:short_name => 'Maldives', :alpha3 => 'MDV', :alpha2 => 'MV', :numcode => 462)
    Country.create(:short_name => 'Mali', :alpha3 => 'MLI', :alpha2 => 'ML', :numcode => 466)
    Country.create(:short_name => 'Malta', :alpha3 => 'MLT', :alpha2 => 'MT', :numcode => 470)
    Country.create(:short_name => 'Marshall Islands', :alpha3 => 'MHL', :alpha2 => 'MH', :numcode => 584)
    Country.create(:short_name => 'Martinique', :alpha3 => 'MTQ', :alpha2 => 'MQ', :numcode => 474)
    Country.create(:short_name => 'Mauritania', :alpha3 => 'MRT', :alpha2 => 'MR', :numcode => 478)
    Country.create(:short_name => 'Mauritius', :alpha3 => 'MUS', :alpha2 => 'MU', :numcode => 480)
    Country.create(:short_name => 'Mayotte', :alpha3 => 'MYT', :alpha2 => 'YT', :numcode => 175)
    Country.create(:short_name => 'Mexico', :alpha3 => 'MEX', :alpha2 => 'MX', :numcode => 484)
    Country.create(:short_name => 'Micronesia, Federated States of', :alpha3 => 'FSM', :alpha2 => 'FM', :numcode => 583)
    Country.create(:short_name => 'Moldova, Republic of', :alpha3 => 'MDA', :alpha2 => 'MD', :numcode => 498)
    Country.create(:short_name => 'Monaco', :alpha3 => 'MCO', :alpha2 => 'MC', :numcode => 492)
    Country.create(:short_name => 'Mongolia', :alpha3 => 'MNG', :alpha2 => 'MN', :numcode => 496)
    Country.create(:short_name => 'Montenegro', :alpha3 => 'MNE', :alpha2 => 'ME', :numcode => 499)
    Country.create(:short_name => 'Montserrat', :alpha3 => 'MSR', :alpha2 => 'MS', :numcode => 500)
    Country.create(:short_name => 'Morocco', :alpha3 => 'MAR', :alpha2 => 'MA', :numcode => 504)
    Country.create(:short_name => 'Mozambique', :alpha3 => 'MOZ', :alpha2 => 'MZ', :numcode => 508)
    Country.create(:short_name => 'Myanmar', :alpha3 => 'MMR', :alpha2 => 'MM', :numcode => 104)
    Country.create(:short_name => 'Namibia', :alpha3 => 'NAM', :alpha2 => 'NA', :numcode => 516)
    Country.create(:short_name => 'Nauru', :alpha3 => 'NRU', :alpha2 => 'NR', :numcode => 520)
    Country.create(:short_name => 'Nepal', :alpha3 => 'NPL', :alpha2 => 'NP', :numcode => 524)
    Country.create(:short_name => 'Netherlands', :alpha3 => 'NLD', :alpha2 => 'NL', :numcode => 528)
    Country.create(:short_name => 'Netherlands Antilles', :alpha3 => 'ANT', :alpha2 => 'AN', :numcode => 530)
    Country.create(:short_name => 'New Caledonia', :alpha3 => 'NCL', :alpha2 => 'NC', :numcode => 540)
    Country.create(:short_name => 'New Zealand', :alpha3 => 'NZL', :alpha2 => 'NZ', :numcode => 554)
    Country.create(:short_name => 'Nicaragua', :alpha3 => 'NIC', :alpha2 => 'NI', :numcode => 558)
    Country.create(:short_name => 'Niger', :alpha3 => 'NER', :alpha2 => 'NE', :numcode => 562)
    Country.create(:short_name => 'Nigeria', :alpha3 => 'NGA', :alpha2 => 'NG', :numcode => 566)
    Country.create(:short_name => 'Niue', :alpha3 => 'NIU', :alpha2 => 'NU', :numcode => 570)
    Country.create(:short_name => 'Norfolk Island', :alpha3 => 'NFK', :alpha2 => 'NF', :numcode => 574)
    Country.create(:short_name => 'Northern Mariana Islands', :alpha3 => 'MNP', :alpha2 => 'MP', :numcode => 580)
    Country.create(:short_name => 'Norway', :alpha3 => 'NOR', :alpha2 => 'NO', :numcode => 578)
    Country.create(:short_name => 'Oman', :alpha3 => 'OMN', :alpha2 => 'OM', :numcode => 512)
    Country.create(:short_name => 'Pakistan', :alpha3 => 'PAK', :alpha2 => 'PK', :numcode => 586)
    Country.create(:short_name => 'Palau', :alpha3 => 'PLW', :alpha2 => 'PW', :numcode => 585)
    Country.create(:short_name => 'Palestinian Territory, Occupied', :alpha3 => 'PSE', :alpha2 => 'PS', :numcode => 275)
    Country.create(:short_name => 'Panama', :alpha3 => 'PAN', :alpha2 => 'PA', :numcode => 591)
    Country.create(:short_name => 'Papua New Guinea', :alpha3 => 'PNG', :alpha2 => 'PG', :numcode => 598)
    Country.create(:short_name => 'Paraguay', :alpha3 => 'PRY', :alpha2 => 'PY', :numcode => 600)
    Country.create(:short_name => 'Peru', :alpha3 => 'PER', :alpha2 => 'PE', :numcode => 604)
    Country.create(:short_name => 'Philippines', :alpha3 => 'PHL', :alpha2 => 'PH', :numcode => 608)
    Country.create(:short_name => 'Pitcairn', :alpha3 => 'PCN', :alpha2 => 'PN', :numcode => 612)
    Country.create(:short_name => 'Poland', :alpha3 => 'POL', :alpha2 => 'PL', :numcode => 616)
    Country.create(:short_name => 'Portugal', :alpha3 => 'PRT', :alpha2 => 'PT', :numcode => 620)
    Country.create(:short_name => 'Puerto Rico', :alpha3 => 'PRI', :alpha2 => 'PR', :numcode => 630)
    Country.create(:short_name => 'Qatar', :alpha3 => 'QAT', :alpha2 => 'QA', :numcode => 634)
    Country.create(:short_name => 'Romania', :alpha3 => 'ROU', :alpha2 => 'RO', :numcode => 642)
    Country.create(:short_name => 'Russian Federation', :alpha3 => 'RUS', :alpha2 => 'RU', :numcode => 643)
    Country.create(:short_name => 'Rwanda', :alpha3 => 'RWA', :alpha2 => 'RW', :numcode => 646)
    Country.create(:short_name => 'Réunion', :alpha3 => 'REU', :alpha2 => 'RE', :numcode => 638)
    Country.create(:short_name => 'Saint Barthélemy', :alpha3 => 'BLM', :alpha2 => 'BL', :numcode => 652)
    Country.create(:short_name => 'Saint Helena', :alpha3 => 'SHN', :alpha2 => 'SH', :numcode => 654)
    Country.create(:short_name => 'Saint Kitts and Nevis', :alpha3 => 'KNA', :alpha2 => 'KN', :numcode => 659)
    Country.create(:short_name => 'Saint Lucia', :alpha3 => 'LCA', :alpha2 => 'LC', :numcode => 662)
    Country.create(:short_name => 'Saint Martin (French part)', :alpha3 => 'MAF', :alpha2 => 'MF', :numcode => 663)
    Country.create(:short_name => 'Saint Pierre and Miquelon', :alpha3 => 'SPM', :alpha2 => 'PM', :numcode => 666)
    Country.create(:short_name => 'Saint Vincent and the Grenadines', :alpha3 => 'VCT', :alpha2 => 'VC', :numcode => 670)
    Country.create(:short_name => 'Samoa', :alpha3 => 'WSM', :alpha2 => 'WS', :numcode => 882)
    Country.create(:short_name => 'San Marino', :alpha3 => 'SMR', :alpha2 => 'SM', :numcode => 674)
    Country.create(:short_name => 'Sao Tome and Principe', :alpha3 => 'STP', :alpha2 => 'ST', :numcode => 678)
    Country.create(:short_name => 'Saudi Arabia', :alpha3 => 'SAU', :alpha2 => 'SA', :numcode => 682)
    Country.create(:short_name => 'Senegal', :alpha3 => 'SEN', :alpha2 => 'SN', :numcode => 686)
    Country.create(:short_name => 'Serbia', :alpha3 => 'SRB', :alpha2 => 'RS', :numcode => 688)
    Country.create(:short_name => 'Seychelles', :alpha3 => 'SYC', :alpha2 => 'SC', :numcode => 690)
    Country.create(:short_name => 'Sierra Leone', :alpha3 => 'SLE', :alpha2 => 'SL', :numcode => 694)
    Country.create(:short_name => 'Singapore', :alpha3 => 'SGP', :alpha2 => 'SG', :numcode => 702)
    Country.create(:short_name => 'Slovakia', :alpha3 => 'SVK', :alpha2 => 'SK', :numcode => 703)
    Country.create(:short_name => 'Slovenia', :alpha3 => 'SVN', :alpha2 => 'SI', :numcode => 705)
    Country.create(:short_name => 'Solomon Islands', :alpha3 => 'SLB', :alpha2 => 'SB', :numcode => 90)
    Country.create(:short_name => 'Somalia', :alpha3 => 'SOM', :alpha2 => 'SO', :numcode => 706)
    Country.create(:short_name => 'South Africa', :alpha3 => 'ZAF', :alpha2 => 'ZA', :numcode => 710)
    Country.create(:short_name => 'South Georgia and the South Sandwich Islands', :alpha3 => 'SGS', :alpha2 => 'GS', :numcode => 239)
    Country.create(:short_name => 'Spain', :alpha3 => 'ESP', :alpha2 => 'ES', :numcode => 724)
    Country.create(:short_name => 'Sri Lanka', :alpha3 => 'LKA', :alpha2 => 'LK', :numcode => 144)
    Country.create(:short_name => 'Sudan', :alpha3 => 'SDN', :alpha2 => 'SD', :numcode => 736)
    Country.create(:short_name => 'Suriname', :alpha3 => 'SUR', :alpha2 => 'SR', :numcode => 740)
    Country.create(:short_name => 'Svalbard and Jan Mayen', :alpha3 => 'SJM', :alpha2 => 'SJ', :numcode => 744)
    Country.create(:short_name => 'Swaziland', :alpha3 => 'SWZ', :alpha2 => 'SZ', :numcode => 748)
    Country.create(:short_name => 'Sweden', :alpha3 => 'SWE', :alpha2 => 'SE', :numcode => 752)
    Country.create(:short_name => 'Switzerland', :alpha3 => 'CHE', :alpha2 => 'CH', :numcode => 756)
    Country.create(:short_name => 'Syrian Arab Republic', :alpha3 => 'SYR', :alpha2 => 'SY', :numcode => 760)
    Country.create(:short_name => 'Taiwan, Province of China', :alpha3 => 'TWN', :alpha2 => 'TW', :numcode => 158)
    Country.create(:short_name => 'Tajikistan', :alpha3 => 'TJK', :alpha2 => 'TJ', :numcode => 762)
    Country.create(:short_name => 'Tanzania, United Republic of', :alpha3 => 'TZA', :alpha2 => 'TZ', :numcode => 834)
    Country.create(:short_name => 'Thailand', :alpha3 => 'THA', :alpha2 => 'TH', :numcode => 764)
    Country.create(:short_name => 'Timor-Leste', :alpha3 => 'TLS', :alpha2 => 'TL', :numcode => 626)
    Country.create(:short_name => 'Togo', :alpha3 => 'TGO', :alpha2 => 'TG', :numcode => 768)
    Country.create(:short_name => 'Tokelau', :alpha3 => 'TKL', :alpha2 => 'TK', :numcode => 772)
    Country.create(:short_name => 'Tonga', :alpha3 => 'TON', :alpha2 => 'TO', :numcode => 776)
    Country.create(:short_name => 'Trinidad and Tobago', :alpha3 => 'TTO', :alpha2 => 'TT', :numcode => 780)
    Country.create(:short_name => 'Tunisia', :alpha3 => 'TUN', :alpha2 => 'TN', :numcode => 788)
    Country.create(:short_name => 'Turkey', :alpha3 => 'TUR', :alpha2 => 'TR', :numcode => 792)
    Country.create(:short_name => 'Turkmenistan', :alpha3 => 'TKM', :alpha2 => 'TM', :numcode => 795)
    Country.create(:short_name => 'Turks and Caicos Islands', :alpha3 => 'TCA', :alpha2 => 'TC', :numcode => 796)
    Country.create(:short_name => 'Tuvalu', :alpha3 => 'TUV', :alpha2 => 'TV', :numcode => 798)
    Country.create(:short_name => 'Uganda', :alpha3 => 'UGA', :alpha2 => 'UG', :numcode => 800)
    Country.create(:short_name => 'Ukraine', :alpha3 => 'UKR', :alpha2 => 'UA', :numcode => 804)
    Country.create(:short_name => 'United Arab Emirates', :alpha3 => 'ARE', :alpha2 => 'AE', :numcode => 784)
    Country.create(:short_name => 'United Kingdom', :alpha3 => 'GBR', :alpha2 => 'GB', :numcode => 826)
    Country.create(:short_name => 'United States', :alpha3 => 'USA', :alpha2 => 'US', :numcode => 840)
    Country.create(:short_name => 'United States Minor Outlying Islands', :alpha3 => 'UMI', :alpha2 => 'UM', :numcode => 581)
    Country.create(:short_name => 'Uruguay', :alpha3 => 'URY', :alpha2 => 'UY', :numcode => 858)
    Country.create(:short_name => 'Uzbekistan', :alpha3 => 'UZB', :alpha2 => 'UZ', :numcode => 860)
    Country.create(:short_name => 'Vanuatu', :alpha3 => 'VUT', :alpha2 => 'VU', :numcode => 548)
    Country.create(:short_name => 'Venezuela', :alpha3 => 'VEN', :alpha2 => 'VE', :numcode => 862)
    Country.create(:short_name => 'Viet Nam', :alpha3 => 'VNM', :alpha2 => 'VN', :numcode => 704)
    Country.create(:short_name => 'Virgin Islands, British', :alpha3 => 'VGB', :alpha2 => 'VG', :numcode => 92)
    Country.create(:short_name => 'Virgin Islands, U.S.', :alpha3 => 'VIR', :alpha2 => 'VI', :numcode => 850)
    Country.create(:short_name => 'Wallis and Futuna', :alpha3 => 'WLF', :alpha2 => 'WF', :numcode => 876)
    Country.create(:short_name => 'Western Sahara', :alpha3 => 'ESH', :alpha2 => 'EH', :numcode => 732)
    Country.create(:short_name => 'Yemen', :alpha3 => 'YEM', :alpha2 => 'YE', :numcode => 887)
    Country.create(:short_name => 'Zambia', :alpha3 => 'ZMB', :alpha2 => 'ZM', :numcode => 894)
    Country.create(:short_name => 'Zimbabwe', :alpha3 => 'ZWE', :alpha2 => 'ZW', :numcode => 716)
  end

  def self.down
    drop_table :countries
  end
end
