module CountryList
  countries = [
    { short_name: 'Afghanistan', alpha3: 'AFG', alpha2: 'AF', numeric: 4 },
    { short_name: 'Åland Islands', alpha3: 'ALA', alpha2: 'AX', numeric: 248 },
    { short_name: 'Albania', alpha3: 'ALB', alpha2: 'AL', numeric: 8 },
    { short_name: 'Algeria', alpha3: 'DZA', alpha2: 'DZ', numeric: 12 },
    { short_name: 'American Samoa', alpha3: 'ASM', alpha2: 'AS', numeric: 16 },
    { short_name: 'Andorra', alpha3: 'AND', alpha2: 'AD', numeric: 20 },
    { short_name: 'Angola', alpha3: 'AGO', alpha2: 'AO', numeric: 24 },
    { short_name: 'Anguilla', alpha3: 'AIA', alpha2: 'AI', numeric: 660 },
    { short_name: 'Antarctica', alpha3: 'ATA', alpha2: 'AQ', numeric: 10 },
    { short_name: 'Antigua and Barbuda', alpha3: 'ATG', alpha2: 'AG', numeric: 28 },
    { short_name: 'Argentina', alpha3: 'ARG', alpha2: 'AR', numeric: 32 },
    { short_name: 'Armenia', alpha3: 'ARM', alpha2: 'AM', numeric: 51 },
    { short_name: 'Aruba', alpha3: 'ABW', alpha2: 'AW', numeric: 533 },
    { short_name: 'Australia', alpha3: 'AUS', alpha2: 'AU', numeric: 36 },
    { short_name: 'Austria', alpha3: 'AUT', alpha2: 'AT', numeric: 40 },
    { short_name: 'Azerbaijan', alpha3: 'AZE', alpha2: 'AZ', numeric: 31 },
    { short_name: 'Bahamas', alpha3: 'BHS', alpha2: 'BS', numeric: 44 },
    { short_name: 'Bahrain', alpha3: 'BHR', alpha2: 'BH', numeric: 48 },
    { short_name: 'Bangladesh', alpha3: 'BGD', alpha2: 'BD', numeric: 50 },
    { short_name: 'Barbados', alpha3: 'BRB', alpha2: 'BB', numeric: 52 },
    { short_name: 'Belarus', alpha3: 'BLR', alpha2: 'BY', numeric: 112 },
    { short_name: 'Belgium', alpha3: 'BEL', alpha2: 'BE', numeric: 56 },
    { short_name: 'Belize', alpha3: 'BLZ', alpha2: 'BZ', numeric: 84 },
    { short_name: 'Benin', alpha3: 'BEN', alpha2: 'BJ', numeric: 204 },
    { short_name: 'Bermuda', alpha3: 'BMU', alpha2: 'BM', numeric: 60 },
    { short_name: 'Bhutan', alpha3: 'BTN', alpha2: 'BT', numeric: 64 },
    { short_name: 'Bolivia', alpha3: 'BOL', alpha2: 'BO', numeric: 68 },
    { short_name: 'Bosnia and Herzegovina', alpha3: 'BIH', alpha2: 'BA', numeric: 70 },
    { short_name: 'Botswana', alpha3: 'BWA', alpha2: 'BW', numeric: 72 },
    { short_name: 'Bouvet Island', alpha3: 'BVT', alpha2: 'BV', numeric: 74 },
    { short_name: 'Brazil', alpha3: 'BRA', alpha2: 'BR', numeric: 76 },
    { short_name: 'British Indian Ocean Territory', alpha3: 'IOT', alpha2: 'IO', numeric: 86 },
    { short_name: 'Brunei Darussalam', alpha3: 'BRN', alpha2: 'BN', numeric: 96 },
    { short_name: 'Bulgaria', alpha3: 'BGR', alpha2: 'BG', numeric: 100 },
    { short_name: 'Burkina Faso', alpha3: 'BFA', alpha2: 'BF', numeric: 854 },
    { short_name: 'Burundi', alpha3: 'BDI', alpha2: 'BI', numeric: 108 },
    { short_name: 'Cambodia', alpha3: 'KHM', alpha2: 'KH', numeric: 116 },
    { short_name: 'Cameroon', alpha3: 'CMR', alpha2: 'CM', numeric: 120 },
    { short_name: 'Canada', alpha3: 'CAN', alpha2: 'CA', numeric: 124 },
    { short_name: 'Cape Verde', alpha3: 'CPV', alpha2: 'CV', numeric: 132 },
    { short_name: 'Cayman Islands', alpha3: 'CYM', alpha2: 'KY', numeric: 136 },
    { short_name: 'Central African Republic', alpha3: 'CAF', alpha2: 'CF', numeric: 140 },
    { short_name: 'Chad', alpha3: 'TCD', alpha2: 'TD', numeric: 148 },
    { short_name: 'Chile', alpha3: 'CHL', alpha2: 'CL', numeric: 152 },
    { short_name: 'China', alpha3: 'CHN', alpha2: 'CN', numeric: 156 },
    { short_name: 'Christmas Island', alpha3: 'CXR', alpha2: 'CX', numeric: 162 },
    { short_name: 'Cocos (Keeling}, Islands', alpha3: 'CCK', alpha2: 'CC', numeric: 166 },
    { short_name: 'Colombia', alpha3: 'COL', alpha2: 'CO', numeric: 170 },
    { short_name: 'Comoros', alpha3: 'COM', alpha2: 'KM', numeric: 174 },
    { short_name: 'Congo', alpha3: 'COG', alpha2: 'CG', numeric: 178 },
    { short_name: 'Congo, the Democratic Republic of the', alpha3: 'COD', alpha2: 'CD', numeric: 180 },
    { short_name: 'Cook Islands', alpha3: 'COK', alpha2: 'CK', numeric: 184 },
    { short_name: 'Costa Rica', alpha3: 'CRI', alpha2: 'CR', numeric: 188 },
    { short_name: 'Croatia', alpha3: 'HRV', alpha2: 'HR', numeric: 191 },
    { short_name: 'Cuba', alpha3: 'CUB', alpha2: 'CU', numeric: 192 },
    { short_name: 'Cyprus', alpha3: 'CYP', alpha2: 'CY', numeric: 196 },
    { short_name: 'Czech Republic', alpha3: 'CZE', alpha2: 'CZ', numeric: 203 },
    { short_name: 'Côte d\'Ivoire', alpha3: 'CIV', alpha2: 'CI', numeric: 384 },
    { short_name: 'Denmark', alpha3: 'DNK', alpha2: 'DK', numeric: 208 },
    { short_name: 'Djibouti', alpha3: 'DJI', alpha2: 'DJ', numeric: 262 },
    { short_name: 'Dominica', alpha3: 'DMA', alpha2: 'DM', numeric: 212 },
    { short_name: 'Dominican Republic', alpha3: 'DOM', alpha2: 'DO', numeric: 214 },
    { short_name: 'Ecuador', alpha3: 'ECU', alpha2: 'EC', numeric: 218 },
    { short_name: 'Egypt', alpha3: 'EGY', alpha2: 'EG', numeric: 818 },
    { short_name: 'El Salvador', alpha3: 'SLV', alpha2: 'SV', numeric: 222 },
    { short_name: 'Equatorial Guinea', alpha3: 'GNQ', alpha2: 'GQ', numeric: 226 },
    { short_name: 'Eritrea', alpha3: 'ERI', alpha2: 'ER', numeric: 232 },
    { short_name: 'Estonia', alpha3: 'EST', alpha2: 'EE', numeric: 233 },
    { short_name: 'Ethiopia', alpha3: 'ETH', alpha2: 'ET', numeric: 231 },
    { short_name: 'Falkland Islands (Malvinas},', alpha3: 'FLK', alpha2: 'FK', numeric: 238 },
    { short_name: 'Faroe Islands', alpha3: 'FRO', alpha2: 'FO', numeric: 234 },
    { short_name: 'Fiji', alpha3: 'FJI', alpha2: 'FJ', numeric: 242 },
    { short_name: 'Finland', alpha3: 'FIN', alpha2: 'FI', numeric: 246 },
    { short_name: 'France', alpha3: 'FRA', alpha2: 'FR', numeric: 250 },
    { short_name: 'French Guiana', alpha3: 'GUF', alpha2: 'GF', numeric: 254 },
    { short_name: 'French Polynesia', alpha3: 'PYF', alpha2: 'PF', numeric: 258 },
    { short_name: 'French Southern Territories', alpha3: 'ATF', alpha2: 'TF', numeric: 260 },
    { short_name: 'Gabon', alpha3: 'GAB', alpha2: 'GA', numeric: 266 },
    { short_name: 'Gambia', alpha3: 'GMB', alpha2: 'GM', numeric: 270 },
    { short_name: 'Georgia', alpha3: 'GEO', alpha2: 'GE', numeric: 268 },
    { short_name: 'Germany', alpha3: 'DEU', alpha2: 'DE', numeric: 276 },
    { short_name: 'Ghana', alpha3: 'GHA', alpha2: 'GH', numeric: 288 },
    { short_name: 'Gibraltar', alpha3: 'GIB', alpha2: 'GI', numeric: 292 },
    { short_name: 'Greece', alpha3: 'GRC', alpha2: 'GR', numeric: 300 },
    { short_name: 'Greenland', alpha3: 'GRL', alpha2: 'GL', numeric: 304 },
    { short_name: 'Grenada', alpha3: 'GRD', alpha2: 'GD', numeric: 308 },
    { short_name: 'Guadeloupe', alpha3: 'GLP', alpha2: 'GP', numeric: 312 },
    { short_name: 'Guam', alpha3: 'GUM', alpha2: 'GU', numeric: 316 },
    { short_name: 'Guatemala', alpha3: 'GTM', alpha2: 'GT', numeric: 320 },
    { short_name: 'Guernsey', alpha3: 'GGY', alpha2: 'GG', numeric: 831 },
    { short_name: 'Guinea', alpha3: 'GIN', alpha2: 'GN', numeric: 324 },
    { short_name: 'Guinea-Bissau', alpha3: 'GNB', alpha2: 'GW', numeric: 624 },
    { short_name: 'Guyana', alpha3: 'GUY', alpha2: 'GY', numeric: 328 },
    { short_name: 'Haiti', alpha3: 'HTI', alpha2: 'HT', numeric: 332 },
    { short_name: 'Heard Island and McDonald Islands', alpha3: 'HMD', alpha2: 'HM', numeric: 334 },
    { short_name: 'Holy See (Vatican City State},', alpha3: 'VAT', alpha2: 'VA', numeric: 336 },
    { short_name: 'Honduras', alpha3: 'HND', alpha2: 'HN', numeric: 340 },
    { short_name: 'Hong Kong', alpha3: 'HKG', alpha2: 'HK', numeric: 344 },
    { short_name: 'Hungary', alpha3: 'HUN', alpha2: 'HU', numeric: 348 },
    { short_name: 'Iceland', alpha3: 'ISL', alpha2: 'IS', numeric: 352 },
    { short_name: 'India', alpha3: 'IND', alpha2: 'IN', numeric: 356 },
    { short_name: 'Indonesia', alpha3: 'IDN', alpha2: 'ID', numeric: 360 },
    { short_name: 'Iran, Islamic Republic of', alpha3: 'IRN', alpha2: 'IR', numeric: 364 },
    { short_name: 'Iraq', alpha3: 'IRQ', alpha2: 'IQ', numeric: 368 },
    { short_name: 'Ireland', alpha3: 'IRL', alpha2: 'IE', numeric: 372 },
    { short_name: 'Isle of Man', alpha3: 'IMN', alpha2: 'IM', numeric: 833 },
    { short_name: 'Israel', alpha3: 'ISR', alpha2: 'IL', numeric: 376 },
    { short_name: 'Italy', alpha3: 'ITA', alpha2: 'IT', numeric: 380 },
    { short_name: 'Jamaica', alpha3: 'JAM', alpha2: 'JM', numeric: 388 },
    { short_name: 'Japan', alpha3: 'JPN', alpha2: 'JP', numeric: 392 },
    { short_name: 'Jersey', alpha3: 'JEY', alpha2: 'JE', numeric: 832 },
    { short_name: 'Jordan', alpha3: 'JOR', alpha2: 'JO', numeric: 400 },
    { short_name: 'Kazakhstan', alpha3: 'KAZ', alpha2: 'KZ', numeric: 398 },
    { short_name: 'Kenya', alpha3: 'KEN', alpha2: 'KE', numeric: 404 },
    { short_name: 'Kiribati', alpha3: 'KIR', alpha2: 'KI', numeric: 296 },
    { short_name: 'Korea, Democratic People\'s Republic of', alpha3: 'PRK', alpha2: 'KP', numeric: 408 },
    { short_name: 'Korea, Republic of', alpha3: 'KOR', alpha2: 'KR', numeric: 410 },
    { short_name: 'Kuwait', alpha3: 'KWT', alpha2: 'KW', numeric: 414 },
    { short_name: 'Kyrgyzstan', alpha3: 'KGZ', alpha2: 'KG', numeric: 417 },
    { short_name: 'Lao People\'s Democratic Republic', alpha3: 'LAO', alpha2: 'LA', numeric: 418 },
    { short_name: 'Latvia', alpha3: 'LVA', alpha2: 'LV', numeric: 428 },
    { short_name: 'Lebanon', alpha3: 'LBN', alpha2: 'LB', numeric: 422 },
    { short_name: 'Lesotho', alpha3: 'LSO', alpha2: 'LS', numeric: 426 },
    { short_name: 'Liberia', alpha3: 'LBR', alpha2: 'LR', numeric: 430 },
    { short_name: 'Libyan Arab Jamahiriya', alpha3: 'LBY', alpha2: 'LY', numeric: 434 },
    { short_name: 'Liechtenstein', alpha3: 'LIE', alpha2: 'LI', numeric: 438 },
    { short_name: 'Lithuania', alpha3: 'LTU', alpha2: 'LT', numeric: 440 },
    { short_name: 'Luxembourg', alpha3: 'LUX', alpha2: 'LU', numeric: 442 },
    { short_name: 'Macao', alpha3: 'MAC', alpha2: 'MO', numeric: 446 },
    { short_name: 'Macedonia, the former Yugoslav Republic of', alpha3: 'MKD', alpha2: 'MK', numeric: 807 },
    { short_name: 'Madagascar', alpha3: 'MDG', alpha2: 'MG', numeric: 450 },
    { short_name: 'Malawi', alpha3: 'MWI', alpha2: 'MW', numeric: 454 },
    { short_name: 'Malaysia', alpha3: 'MYS', alpha2: 'MY', numeric: 458 },
    { short_name: 'Maldives', alpha3: 'MDV', alpha2: 'MV', numeric: 462 },
    { short_name: 'Mali', alpha3: 'MLI', alpha2: 'ML', numeric: 466 },
    { short_name: 'Malta', alpha3: 'MLT', alpha2: 'MT', numeric: 470 },
    { short_name: 'Marshall Islands', alpha3: 'MHL', alpha2: 'MH', numeric: 584 },
    { short_name: 'Martinique', alpha3: 'MTQ', alpha2: 'MQ', numeric: 474 },
    { short_name: 'Mauritania', alpha3: 'MRT', alpha2: 'MR', numeric: 478 },
    { short_name: 'Mauritius', alpha3: 'MUS', alpha2: 'MU', numeric: 480 },
    { short_name: 'Mayotte', alpha3: 'MYT', alpha2: 'YT', numeric: 175 },
    { short_name: 'Mexico', alpha3: 'MEX', alpha2: 'MX', numeric: 484 },
    { short_name: 'Micronesia, Federated States of', alpha3: 'FSM', alpha2: 'FM', numeric: 583 },
    { short_name: 'Moldova, Republic of', alpha3: 'MDA', alpha2: 'MD', numeric: 498 },
    { short_name: 'Monaco', alpha3: 'MCO', alpha2: 'MC', numeric: 492 },
    { short_name: 'Mongolia', alpha3: 'MNG', alpha2: 'MN', numeric: 496 },
    { short_name: 'Montenegro', alpha3: 'MNE', alpha2: 'ME', numeric: 499 },
    { short_name: 'Montserrat', alpha3: 'MSR', alpha2: 'MS', numeric: 500 },
    { short_name: 'Morocco', alpha3: 'MAR', alpha2: 'MA', numeric: 504 },
    { short_name: 'Mozambique', alpha3: 'MOZ', alpha2: 'MZ', numeric: 508 },
    { short_name: 'Myanmar', alpha3: 'MMR', alpha2: 'MM', numeric: 104 },
    { short_name: 'Namibia', alpha3: 'NAM', alpha2: 'NA', numeric: 516 },
    { short_name: 'Nauru', alpha3: 'NRU', alpha2: 'NR', numeric: 520 },
    { short_name: 'Nepal', alpha3: 'NPL', alpha2: 'NP', numeric: 524 },
    { short_name: 'Netherlands', alpha3: 'NLD', alpha2: 'NL', numeric: 528 },
    { short_name: 'Netherlands Antilles', alpha3: 'ANT', alpha2: 'AN', numeric: 530 },
    { short_name: 'New Caledonia', alpha3: 'NCL', alpha2: 'NC', numeric: 540 },
    { short_name: 'New Zealand', alpha3: 'NZL', alpha2: 'NZ', numeric: 554 },
    { short_name: 'Nicaragua', alpha3: 'NIC', alpha2: 'NI', numeric: 558 },
    { short_name: 'Niger', alpha3: 'NER', alpha2: 'NE', numeric: 562 },
    { short_name: 'Nigeria', alpha3: 'NGA', alpha2: 'NG', numeric: 566 },
    { short_name: 'Niue', alpha3: 'NIU', alpha2: 'NU', numeric: 570 },
    { short_name: 'Norfolk Island', alpha3: 'NFK', alpha2: 'NF', numeric: 574 },
    { short_name: 'Northern Mariana Islands', alpha3: 'MNP', alpha2: 'MP', numeric: 580 },
    { short_name: 'Norway', alpha3: 'NOR', alpha2: 'NO', numeric: 578 },
    { short_name: 'Oman', alpha3: 'OMN', alpha2: 'OM', numeric: 512 },
    { short_name: 'Pakistan', alpha3: 'PAK', alpha2: 'PK', numeric: 586 },
    { short_name: 'Palau', alpha3: 'PLW', alpha2: 'PW', numeric: 585 },
    { short_name: 'Palestinian Territory, Occupied', alpha3: 'PSE', alpha2: 'PS', numeric: 275 },
    { short_name: 'Panama', alpha3: 'PAN', alpha2: 'PA', numeric: 591 },
    { short_name: 'Papua New Guinea', alpha3: 'PNG', alpha2: 'PG', numeric: 598 },
    { short_name: 'Paraguay', alpha3: 'PRY', alpha2: 'PY', numeric: 600 },
    { short_name: 'Peru', alpha3: 'PER', alpha2: 'PE', numeric: 604 },
    { short_name: 'Philippines', alpha3: 'PHL', alpha2: 'PH', numeric: 608 },
    { short_name: 'Pitcairn', alpha3: 'PCN', alpha2: 'PN', numeric: 612 },
    { short_name: 'Poland', alpha3: 'POL', alpha2: 'PL', numeric: 616 },
    { short_name: 'Portugal', alpha3: 'PRT', alpha2: 'PT', numeric: 620 },
    { short_name: 'Puerto Rico', alpha3: 'PRI', alpha2: 'PR', numeric: 630 },
    { short_name: 'Qatar', alpha3: 'QAT', alpha2: 'QA', numeric: 634 },
    { short_name: 'Romania', alpha3: 'ROU', alpha2: 'RO', numeric: 642 },
    { short_name: 'Russian Federation', alpha3: 'RUS', alpha2: 'RU', numeric: 643 },
    { short_name: 'Rwanda', alpha3: 'RWA', alpha2: 'RW', numeric: 646 },
    { short_name: 'Réunion', alpha3: 'REU', alpha2: 'RE', numeric: 638 },
    { short_name: 'Saint Barthélemy', alpha3: 'BLM', alpha2: 'BL', numeric: 652 },
    { short_name: 'Saint Helena', alpha3: 'SHN', alpha2: 'SH', numeric: 654 },
    { short_name: 'Saint Kitts and Nevis', alpha3: 'KNA', alpha2: 'KN', numeric: 659 },
    { short_name: 'Saint Lucia', alpha3: 'LCA', alpha2: 'LC', numeric: 662 },
    { short_name: 'Saint Martin (French part},', alpha3: 'MAF', alpha2: 'MF', numeric: 663 },
    { short_name: 'Saint Pierre and Miquelon', alpha3: 'SPM', alpha2: 'PM', numeric: 666 },
    { short_name: 'Saint Vincent and the Grenadines', alpha3: 'VCT', alpha2: 'VC', numeric: 670 },
    { short_name: 'Samoa', alpha3: 'WSM', alpha2: 'WS', numeric: 882 },
    { short_name: 'San Marino', alpha3: 'SMR', alpha2: 'SM', numeric: 674 },
    { short_name: 'Sao Tome and Principe', alpha3: 'STP', alpha2: 'ST', numeric: 678 },
    { short_name: 'Saudi Arabia', alpha3: 'SAU', alpha2: 'SA', numeric: 682 },
    { short_name: 'Senegal', alpha3: 'SEN', alpha2: 'SN', numeric: 686 },
    { short_name: 'Serbia', alpha3: 'SRB', alpha2: 'RS', numeric: 688 },
    { short_name: 'Seychelles', alpha3: 'SYC', alpha2: 'SC', numeric: 690 },
    { short_name: 'Sierra Leone', alpha3: 'SLE', alpha2: 'SL', numeric: 694 },
    { short_name: 'Singapore', alpha3: 'SGP', alpha2: 'SG', numeric: 702 },
    { short_name: 'Slovakia', alpha3: 'SVK', alpha2: 'SK', numeric: 703 },
    { short_name: 'Slovenia', alpha3: 'SVN', alpha2: 'SI', numeric: 705 },
    { short_name: 'Solomon Islands', alpha3: 'SLB', alpha2: 'SB', numeric: 90 },
    { short_name: 'Somalia', alpha3: 'SOM', alpha2: 'SO', numeric: 706 },
    { short_name: 'South Africa', alpha3: 'ZAF', alpha2: 'ZA', numeric: 710 },
    { short_name: 'South Georgia and the South Sandwich Islands', alpha3: 'SGS', alpha2: 'GS', numeric: 239 },
    { short_name: 'Spain', alpha3: 'ESP', alpha2: 'ES', numeric: 724 },
    { short_name: 'Sri Lanka', alpha3: 'LKA', alpha2: 'LK', numeric: 144 },
    { short_name: 'Sudan', alpha3: 'SDN', alpha2: 'SD', numeric: 736 },
    { short_name: 'Suriname', alpha3: 'SUR', alpha2: 'SR', numeric: 740 },
    { short_name: 'Svalbard and Jan Mayen', alpha3: 'SJM', alpha2: 'SJ', numeric: 744 },
    { short_name: 'Swaziland', alpha3: 'SWZ', alpha2: 'SZ', numeric: 748 },
    { short_name: 'Sweden', alpha3: 'SWE', alpha2: 'SE', numeric: 752 },
    { short_name: 'Switzerland', alpha3: 'CHE', alpha2: 'CH', numeric: 756 },
    { short_name: 'Syrian Arab Republic', alpha3: 'SYR', alpha2: 'SY', numeric: 760 },
    { short_name: 'Taiwan, Province of China', alpha3: 'TWN', alpha2: 'TW', numeric: 158 },
    { short_name: 'Tajikistan', alpha3: 'TJK', alpha2: 'TJ', numeric: 762 },
    { short_name: 'Tanzania, United Republic of', alpha3: 'TZA', alpha2: 'TZ', numeric: 834 },
    { short_name: 'Thailand', alpha3: 'THA', alpha2: 'TH', numeric: 764 },
    { short_name: 'Timor-Leste', alpha3: 'TLS', alpha2: 'TL', numeric: 626 },
    { short_name: 'Togo', alpha3: 'TGO', alpha2: 'TG', numeric: 768 },
    { short_name: 'Tokelau', alpha3: 'TKL', alpha2: 'TK', numeric: 772 },
    { short_name: 'Tonga', alpha3: 'TON', alpha2: 'TO', numeric: 776 },
    { short_name: 'Trinidad and Tobago', alpha3: 'TTO', alpha2: 'TT', numeric: 780 },
    { short_name: 'Tunisia', alpha3: 'TUN', alpha2: 'TN', numeric: 788 },
    { short_name: 'Turkey', alpha3: 'TUR', alpha2: 'TR', numeric: 792 },
    { short_name: 'Turkmenistan', alpha3: 'TKM', alpha2: 'TM', numeric: 795 },
    { short_name: 'Turks and Caicos Islands', alpha3: 'TCA', alpha2: 'TC', numeric: 796 },
    { short_name: 'Tuvalu', alpha3: 'TUV', alpha2: 'TV', numeric: 798 },
    { short_name: 'Uganda', alpha3: 'UGA', alpha2: 'UG', numeric: 800 },
    { short_name: 'Ukraine', alpha3: 'UKR', alpha2: 'UA', numeric: 804 },
    { short_name: 'United Arab Emirates', alpha3: 'ARE', alpha2: 'AE', numeric: 784 },
    { short_name: 'United Kingdom', alpha3: 'GBR', alpha2: 'GB', numeric: 826 },
    { short_name: 'United States', alpha3: 'USA', alpha2: 'US', numeric: 840 },
    { short_name: 'United States Minor Outlying Islands', alpha3: 'UMI', alpha2: 'UM', numeric: 581 },
    { short_name: 'Uruguay', alpha3: 'URY', alpha2: 'UY', numeric: 858 },
    { short_name: 'Uzbekistan', alpha3: 'UZB', alpha2: 'UZ', numeric: 860 },
    { short_name: 'Vanuatu', alpha3: 'VUT', alpha2: 'VU', numeric: 548 },
    { short_name: 'Venezuela', alpha3: 'VEN', alpha2: 'VE', numeric: 862 },
    { short_name: 'Viet Nam', alpha3: 'VNM', alpha2: 'VN', numeric: 704 },
    { short_name: 'Virgin Islands, British', alpha3: 'VGB', alpha2: 'VG', numeric: 92 },
    { short_name: 'Virgin Islands, U.S.', alpha3: 'VIR', alpha2: 'VI', numeric: 850 },
    { short_name: 'Wallis and Futuna', alpha3: 'WLF', alpha2: 'WF', numeric: 876 },
    { short_name: 'Western Sahara', alpha3: 'ESH', alpha2: 'EH', numeric: 732 },
    { short_name: 'Yemen', alpha3: 'YEM', alpha2: 'YE', numeric: 887 },
    { short_name: 'Zambia', alpha3: 'ZMB', alpha2: 'ZM', numeric: 894 },
    { short_name: 'Zimbabwe', alpha3: 'ZWE', alpha2: 'ZW', numeric: 716 }
  ]

  ::Country.transaction do
    ::Country.create(countries) if ::Country.first.nil?
  end
end
